--liquibase formatted sql
--changeset junior:202505171257
--comment: spring batch BATCH_JOB_INSTANCE

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

--rollback DROP TABLE BATCH_JOB_INSTANCE;
