spring:
  application:
    name: batchBank
  datasource:
    url: jdbc:postgresql://localhost:5432/batch-banck
    username: batch-banck
    password: batch-banck
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    job:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html


server:
  servlet:
    context-path: /batch-bank